api_login_check:
  path: /api/login_check

users_get:
  path: /api/users/
  controller: App\Controller\UserController::getUsers
  methods: [GET]

user_create:
  path: /api/users/
  controller: App\Controller\UserController::register
  methods: [POST]

user_get:
  path: /api/users/{id}
  controller: App\Controller\UserController::getUserById
  methods: [GET]

user_delete:
  path: /api/users/{id}
  controller: App\Controller\UserController::deleteUser
  methods: [DELETE]

user_update:
  path: /api/users/{id}
  controller: App\Controller\UserController::updateUser
  methods: [PUT]
